### ISSUE TITLE
mysql8.0 problems

### ISSUE THREAD

**Issue by VINO42** [brunorozendo/log4jdbc-log4j2#40]
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.

pom:
		<dependency>
			<groupId>org.bgee.log4jdbc-log4j2</groupId>
			<artifactId>log4jdbc-log4j2-jdbc4.1</artifactId>
			<version>1.16</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
		</dependency>
               		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>8.0.11</version>
		</dependency>

using springboot 1.5.6

**Comment by brunorozendo** [comment]
If you try  ?
`-Dlog4jdbc.auto.load.popular.drivers=false  -Dlog4jdbc.drivers=com.mysql.cj.jdbc.Driver`

**Comment by VINO42** [comment]
ok, what  should I do in the application.properties?

**Comment by VINO42** [comment]
like this?:
log4jdbc.auto.load.popular.drivers=false
log4jdbc.drivers=com.mysql.cj.jdbc.Driver


I will try it

**Comment by brunorozendo** [comment]
The file is `log4jdbc.log4j2.properties`

**Comment by VINO42** [comment]
I just tried 
this is my log4jdbc.log4j2.properties contents:
log4jdbc.spylogdelegator.name=net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator
log4jdbc.auto.load.popular.drivers=false
log4jdbc.drivers=com.mysql.cj.jdbc.Driver

it seems the  log dispeared 


thx!
